name: label-required-approvals
on:
  pull_request_review:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
jobs:
  required-approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lvegerano/label-required-approvals@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
