name: Add Labels

on:
  pull_request:
    paths: 
      - '.github/workflows/label-review.yml'
      - '.github/workflows/block-merge.yml'
      - '.github/workflows/reviewer-update.yml'
      - '.github/team-approvers.yml'

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: add labels
        uses: actions-ecosystem/action-add-labels@main
        with:
          labels: approver-update
